---
use: swarm

plugins:
  - vai

vm: &vm-defaults
  name_prefix: box
  nodes: 1
  box: 'kedwards/debian12'
  memory: 512
  cpus: 1
  os_disk_size: '20GB'
  disks: 1
  disk_size: 10
  disk_type: SATA # IDE | SCSI | SATA
  gui: false
  ansible_use: dns # dns | ip
  check_guest_additions: false
  box_check_update: false
  synced_folder_disabled: true
  ip_addr_prefix: 192.168.56.
  ansible_group:
  customize:
    - description: DNS proxy in NAT mode
      command: --natdnshostresolver1
      value: 'on'
 
swarm:
  - <<: *vm-defaults
    description: HA Proxy
    name: haproxy
    ansible_use: dns
    name_prefix: haproxy
    ip_addr_prefix: 192.168.56.
    ansible_group: proxy_nodes
  - <<: *vm-defaults
    description: Swarm Managers
    name: manager
    nodes: 3
    name_prefix: manager
    ip_addr_prefix: 192.168.56.1
    ansible_group: swarm_managers
  - <<: *vm-defaults
    description: Worker Nodes
    name: worker
    nodes: 3
    name_prefix: worker
    ip_addr_prefix: 192.168.56.2
    ansible_group: swarm_workers
  - description: Provisioner
    name: provisioner
    type: provisioner
    provisioners:
      - description: Hosts Manager
        type: hostsmanager
      - description: Vai provisioner
        type: vai
        path: ../ansible/inventory
        filename: vagrant_ansible_inventory
