---
- name: Install required packages
  ansible.builtin.apt:
    name:
      - apache2-utils
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - libnss3-tools
      - python3-pip
      - software-properties-common
    update_cache: true
