# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "debian-12.11.0.box"
  config.vm.box_check_update = false

  # SSH configuration
  config.ssh.username = "vagrant"
  config.ssh.private_key_path = "/home/kedwards/.ssh/vagrant.id_rsa.pub"

end
