---
- name: setup pre-requisites on non-admin nodes
  hosts: all !admins
  become: yes
  roles:
    - create-sudo-user
    - install-modules
    - configure-hosts-file

- name: setup docker user on admin nodes
  hosts: admins
  become: yes
  become_user: docker
  roles:
    - configure-admin

- name: configure swarm nodes
  hosts: swarm_*
  become: yes
  roles:
    - copy-keys
    - docker-installation
    - docker-swarm-init
    - gluster

- name: configure services
  hosts: swarm_managers[0]
  become: yes
  roles:
    - traefik
    - portainer

- name: install & configure HA Proxy
  hosts: proxy_nodes[0]
  become: yes
  roles:
    - haproxy

