---
- name: Check if swarm has already been initialized
  shell: docker node ls
  register: swarm_status
  ignore_errors: true
  changed_when: false

- name: Add Docker node to existing swarm as worker
  shell: >
    docker swarm join
    --token {{ join_token }} {{ join_address }}
  when: swarm_status.rc != 0
  ignore_errors: true
