---
- name: Initialize docker-swarm
  when: inventory_hostname == groups['swarm_managers'][0]
  block:
    - name: Check if swarm has already been initialized
      ansible.builtin.command: docker node ls
      register: swarm_status
      # changed_when: "'This node is not a swarm manager' not in swarm_status.stderr"
      # changed_when: swarm_status.stdout != ""
      changed_when: false

    - name: Initialize swarm leader
      ansible.builtin.command: docker swarm init --advertise-addr={{ inventory_hostname }}:2377
      changed_when: false
      when: swarm_status.rc != 0

    - name: Get the manager join-token
      ansible.builtin.command: docker swarm join-token --quiet manager
      changed_when: false
      register: manager_token

    - name: Get the worker join-token
      ansible.builtin.command: docker swarm join-token --quiet worker
      changed_when: false
      register: worker_token

- name: Add managers
  ansible.builtin.include_role:
    name: docker-swarm-add-manager
  vars:
    join_token: "{{ hostvars[groups['swarm_managers'][0]]['manager_token']['stdout'] }}"
    join_address: "{{ groups['swarm_managers'][0] }}:2377"
  when: inventory_hostname != groups['swarm_managers'][0] and inventory_hostname in groups['swarm_managers']

- name: Add workers
  ansible.builtin.include_role:
    name: docker-swarm-add-worker
  vars:
    join_token: "{{ hostvars[groups['swarm_managers'][0]]['worker_token']['stdout'] }}"
    join_address: "{{ groups['swarm_managers'][0] }}:2377"
  when: inventory_hostname in groups['swarm_workers'] | default([])
