---
- name: Check if Gluster volume is initialized
  ansible.builtin.stat:
    path: "{{ gluster_volume_path }}/{{ inventory_hostname }}/brick"
  register: glustervolume

- name: Verify Gluster volume path
  file:
    path: "{{ gluster_volume_path }}/{{ inventory_hostname }}/brick"
    state: directory

- name: Initialize Gluster Cluster (on first node)
  shell: gluster peer probe {{ item }}
  loop: "{{ groups['gluster_nodes'] }}"
  when: glustervolume.stat.exists == false and inventory_hostname == groups['gluster_nodes'][0]

- name: Create Gluster Volume (on first node)
  shell: >
    gluster volume create {{ gluster_volume_name }} \
    replica 3 \
    {{ groups['gluster_nodes'][0] }}:{{ gluster_volume_path }}/{{ groups['gluster_nodes'][0] }}/brick \
    {{ groups['gluster_nodes'][1] }}:{{ gluster_volume_path }}/{{ groups['gluster_nodes'][1] }}/brick \
    {{ groups['gluster_nodes'][2] }}:{{ gluster_volume_path }}/{{ groups['gluster_nodes'][2] }}/brick
  when: glustervolume.stat.exists == false and inventory_hostname == groups['gluster_nodes'][0]

- name: Secure Gluster Volume (on first node)
  shell: >
    gluster volume set {{ gluster_volume_name }} auth.allow  \
    {{ groups['gluster_nodes'][0] }},{{ groups['gluster_nodes'][1] }},{{ groups['gluster_nodes'][2] }}
  when: inventory_hostname == groups['gluster_nodes'][0]

- name: Start Gluster Volume (on first node)
  shell: gluster volume start {{ gluster_volume_name }}
  when: glustervolume.stat.exists == false and inventory_hostname == groups['gluster_nodes'][0]

- name: Wait 60s for Gluster volume to be replicated
  shell: sleep 60
  when: glustervolume.stat.exists == false and inventory_hostname == groups['gluster_nodes'][0]
