version: "3.7"

services:

    redis:
        image: redis:5.0.8
        ports:
            - 6380:6380
        # specify port for redis, so other containers can connect to modified port, otherwise 6380 would be exposed only for host
        command:
            -- port 6380
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints: [node.role == manager]
        networks:
            - frontend

    www:
        depends_on:
            - db
            - redis
        image: registry.gitlab.com/sewio/studio/rtls-studio/core:2.5.1
        ports:
            - "80"
            - "443"
            - "5000:5000/udp"
            - "5001:5001/udp"
            - "5000:5000/tcp"
            - "5001:5001/tcp"
            - "5100:5100/udp"
            - "5101:5101/udp"
        volumes:
            - persistent_core_migrate:/home/rtlsserver/migrate
            - persistent_core_plans:/var/www/html/sensmapserver/svgs/uploads/plans
            - persistent_core_rtlsserver:/home/rtlsserver/persistent
            - persistent_core_sewiortls:/home/sewiortls
            - persistent_rtlsio:/home/rtlsio
        deploy:
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.studio.rule=Host(`studio.docker.localhost`)"
                - "traefik.http.services.studio.loadbalancer.server.port=80"
                - "traefik.docker.network=traefik"
            placement:
                constraints: [node.role == manager]
        networks:
            - frontend
        environment:
            LOG_CHANNEL: stderr

            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: rtls_main
            DB_USERNAME: laravel_user
            # DB_PASSWORD_FILE: /run/secrets/db_password
            DB_PASSWORD: sensmap

            DB_HOST_SECOND: db
            DB_PORT_SECOND: 3306
            DB_DATABASE_SECOND: sensmapserver
            DB_USERNAME_SECOND: laravel_user
            # DB_PASSWORD_SECOND_FILE: /run/secrets/db_password
            DB_PASSWORD_SECOND_FILE: sensmap

            REDIS_HOST: redis
            REDIS_PORT: 6380

            PHPMYADMIN_HOST: phpmyadmin
        # secrets:
        #   - db_password
        #   - internal_api_key

    rtlsio:
        depends_on:
            - www
        image: connectglobal/studio_io:2.5.1
        volumes:
            - persistent_rtlsio:/home/rtlsio
        networks:
            - frontend
        environment:
            # JWT_SECRET_FILE: /run/secrets/jwt_secret
            # INTERNAL_API_KEY_FILE: /run/secrets/internal_api_key
            JWT_SECRET: B1Bbr8EnAdJASz3l7WlXXX0U69f4UHsdtDX
            INTERNAL_API_KEY: NFErWZEOD1zoKCEPNiSxLpcg3
            WWW_HOST: www
        # secrets:
        #   - jwt_secret
        #   - internal_api_key

    db:
        image: connectglobal/studio_db:2.5.1
        ports:
            - "3306:3306"
        environment:
            MYSQL_USER: laravel_user
            # MYSQL_PASSWORD_FILE: /run/secrets/db_password
            MYSQL_PASSWORD_FILE: sensmap
            ##########################################################################
            ## MYSQL_ROOT_USERNAME and MYSQL_ROOT_PASSWORD_FILE                      #
            #                                                                        #
            # creates two logins to database: root and sewiortls with                #
            # password defined in secret file db_root_password                       #
            # this is only optional, if you don't want (need) this access,           #
            # you can safely comment MYSQL_ROOT_USERNAME and MYSQL_ROOT_PASWORD_FILE #
            ##########################################################################
            MYSQL_ROOT_USERNAME: sewiortls
            # MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
            # INTERNAL_API_KEY_FILE: /run/secrets/internal_api_key
            MYSQL_ROOT_PASSWORD: sensmap
            INTERNAL_API_KEY_FILE: NFErWZEOD1zoKCEPNiSxLpcg3
        volumes:
            - persistent_db_dump:/docker-entrypoint-initdb.d/
            - persistent:/var/lib/mysql
        networks:
            - frontend
        # secrets:
        #   - db_password
        #   - db_root_password
        #   - internal_api_key

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        # no need to publish ports, www will directly communicate with this container
        networks:
            - frontend
        environment:
            MYSQL_USER: laravel_user
            # MYSQL_PASSWORD_FILE: /run/secrets/db_password
            # MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
            MYSQL_PASSWORD: sensmap
            MYSQL_ROOT_PASSWORD: sensmap
            # in case that studio will be used with https
            # then pma_absolute_uri should be set to https://localhost/phpmyadmin-d/
            # to avoid message in phpmyadmin warning about http and https mismatch
            PMA_ABSOLUTE_URI: /phpmyadmin-d/
        # secrets:
        #   - db_password
        #   - db_root_password

volumes:
  persistent:
    driver: glusterfs
    name: "gfs/studio_mysql_data"
  persistent_db_dump:
    driver: glusterfs
    name: "gfs/studio_mysql_dump"
  persistent_core_migrate:
    driver: glusterfs
    name: "gfs/studio_migrate"
  persistent_core_plans:
    driver: glusterfs
    name: "gfs/studio_plans"
  persistent_core_rtlsserver:
    driver: glusterfs
    name: "gfs/studio_rtlsserver"
  persistent_core_sewiortls:
    driver: glusterfs
    name: "gfs/studio_rtlsserver"
  persistent_rtlsio:
    driver: glusterfs
    name: "gfs/studio_rtlsio"

# secrets:
#     db_password:
#         file: ./secrets/db_password.txt
#     jwt_secret:
#         file: ./secrets/jwt_secret.txt
#     db_root_password:
#         file: ./secrets/db_root_password.txt
#     internal_api_key:
#         file: ./secrets/internal_api_key.txt

networks:
    frontend:
