---
# - name: setup pre-requisites
#   hosts: all
#   become: yes
#   roles:
#     - create-sudo-user
#     - install-modules
#     - configure-hosts-file
#     - disable-auto-update

# - name: setup docker user on the nodes
#   hosts: admin
#   become: yes
#   become_user: docker
#   roles:
#     - configure-admin

# - name: copy public key to nodes
#   hosts: docker_nodes
#   become: yes
#   roles:
#     - copy-keys

# - name: install docker
#   hosts: swarm_*
#   become: yes
#   roles:
#     - docker-installation

# - name: initialize docker swarm
#   hosts: swarm_managers
#   become: yes
#   roles:
#     - docker-swarm-init

# - name: add workers to the swarm
#   hosts: swarm_workers
#   become: yes
#   roles:
#     - docker-swarm-add-worker

# - name: configure storage with GFS
#   hosts: gluster_nodes
#   become: yes
#   roles:
#     - gluster

# - name: configure traefik service
#   hosts: swarm_managers
#   become: yes
#   roles:
#     - traefik
#     - portainer

- name: install & configure HA Proxy
  hosts: proxies
  become: yes
  roles:
    - haproxy

