---
- name: Check if gluster plugin is installed
  ansible.builtin.shell: docker plugin inspect glusterfs
  register: gluster_plugin_status
  changed_when: false

- name: Check if gluster plugin has been initialized
  ansible.builtin.shell: 
    docker plugin ls | grep glusterfs | awk '{print $8}'
  register: gluster_plugin_initialized
  changed_when: false

- name: Configure plugin
  when: gluster_plugin_status.rc != 0 or gluster_update | default(false)
  block:
    - name: Disable docker gluster plugin
      ansible.builtin.command: docker plugin disable -f glusterfs
      changed_when: "'plugin is already disabled' not in gluster_plugin_status.stderr"
      when: gluster_plugin_initialized.stdout == "true"

    - name: Install gluster plugin
      ansible.builtin.command: docker plugin install --alias glusterfs {{ docker_volume_plugin }} --grant-all-permissions --disable
      changed_when: false
      when: gluster_plugin_status.rc != 0

    - name: Build a list of gluster servers
      ansible.builtin.set_fact:
        gluster_server: "{{ ','.join(item) }}"
      with_items: "{{ groups['swarm_managers'] + groups['swarm_workers'] | default([]) }}"

    - name: Set gluster plugin to use gluster nodes
      ansible.builtin.command: docker plugin set glusterfs SERVERS={{ gluster_server }}
      changed_when: false

    - name: Enable gluster plugin
      ansible.builtin.command: docker plugin enable glusterfs
      register: gluster_plugin_enable
      changed_when: false
