---
- name: Create a temporary directory
  ansible.builtin.tempfile:
    state: directory
    suffix: tmp
  register: tmpdir
  changed_when: false

- name: Install python packages
  ansible.builtin.pip:
    name: docker
  when: ansible_distribution == 'Ubuntu'

- name: Install python packages
  ansible.builtin.apt:
    name:
      - python3-docker
    state: present
  when: ansible_distribution == 'Debian'

- name: Install docker
  when: ansible_distribution == 'Ubuntu'
  block:
    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename | lower }} stable
      tags: docker

    - name: Install Docker
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups:
      - docker
    append: true

- name: Start docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Wait for docker service
  ansible.builtin.wait_for:
    path: /var/run/docker.sock
