---
- name: System pre-requisites
  hosts: all
  become: true
  roles:
    - system-packages

- name: Configure all swarm nodes
  hosts: swarm_*
  become: true
  roles:
    - docker
    - docker-swarm-init

- name: Configure gluster nodes
  hosts: gluster_nodes
  become: true
  roles:
    - gluster

- name: Configure HA Proxy
  hosts: proxy_nodes
  become: true
  roles:
    - haproxy

- name: Configure global services
  hosts: swarm_managers[0]
  become: true
  roles:
    - caddy
    - traefik
    - portainer
