---
- name: System pre-requisites
  hosts: all
  become: yes
  roles:
    # - create-user
    - system-packages
    # - hosts-name

# - name: setup docker user on admin nodes
#   hosts: admins
#   become: yes
#   become_user: docker
#   roles:
#    - create-user
#    - configure-admin

- name: configure swarm nodes
  hosts: swarm_*
  become: yes
  roles:
    # - copy-keys
    - docker
    - create-user
    - docker-swarm-init
    - glusterfs

- name: configure global services
  hosts: swarm_managers
  become: yes
  roles:
    - traefik
    - portainer

- name: configure HA Proxy
  hosts: proxy_nodes
  become: yes
  roles:
    - haproxy
