---
- name: Check if Gluster plugin has already been initialized
  shell: docker plugin inspect glusterfs
  register: gluster_plugin_status
  ignore_errors: true

- name: Install Docker Gluster plugin
  shell: "docker plugin install --alias glusterfs {{ docker_volume_plugin }} --grant-all-permissions --disable"
  when: gluster_plugin_status.rc != 0

- name: Build a list of gluster servers.
  set_fact:
    gluster_server_names: "{{ ','.join((groups['gluster_nodes'])) }}"
  with_items: "{{ groups['gluster_nodes'] }}"
  when: gluster_plugin_status.rc != 0

- name: Set Gluster plugin to use Gluster nodes
  shell: docker plugin set glusterfs SERVERS={{ gluster_server_names }}
  when: gluster_plugin_status.rc != 0

- name: Enable Gluster plugin
  shell: docker plugin enable glusterfs
  when: gluster_plugin_status.rc != 0