---
- name: Create a temporary directory
  tempfile:
    state: directory
    suffix: tmp
  register: tmpdir

- name: Install Docker Dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - software-properties-common
    state: latest
    update_cache: yes
  tags: docker

- name: Get Docker key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: docker

- name: Add Docker packages to Repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable
  tags: docker

- name: Install Docker-CE
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: yes
  tags: docker

- name: Start docker service, if not started
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  ignore_errors: true

- name: Waiting for Docker service to become available
  wait_for:
    path: /var/run/docker.sock

- name: Check if Gluster plugin has already been initialized
  shell: docker plugin inspect glusterfs
  register: gluster_plugin_status
  ignore_errors: true

- name: Install Docker Gluster plugin
  shell: docker plugin install --alias glusterfs trajano/glusterfs-volume-plugin --grant-all-permissions --disable
  when: gluster_plugin_status.rc != 0

- name: Set Gluster plugin to use Gluster nodes
  shell: docker plugin set glusterfs SERVERS={{groups['gluster_nodes'][0]}},{{groups['gluster_nodes'][1]}},{{groups['gluster_nodes'][2]}}
  when: gluster_plugin_status.rc != 0

- name: Enable Gluster plugin
  shell: docker plugin enable glusterfs
  when: gluster_plugin_status.rc != 0